name: 'Setup Node.js and project dependencies'

description: 'Set up Node.js version as defined in `.nvmrc`-file, install all dependencies (via npm) and cache them.'

runs:
  using: 'composite'
  steps:
    - name: 'Setup project-specific Node.js version'
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: 'Cache NPM dependencies'
      id: cache-dependencies
      uses: actions/cache@v4
      with:
        path: |
          node_modules
        key: cache-dependencies-${{ hashFiles('**/package-lock.json') }}

    - name: 'Install dependencies (via npm)'
      shell: bash
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: |
        npm ci